---
title: writerror
email: 
description: |
  anarchist news aggregator
baseurl: ''
url: 'http://writerror.com'
twitter_username: writerror
github_username:
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
#permalink: "/:year/:month/:title.html"
permalink: "/texts/:title"
sass:
  style: compressed
javascript:
  style: compressed
